---
- name: Install and unzip Fuse
  hosts: localhost

  tasks:
    - name: Include vars
      include_vars: vars.yml

    - name: download Fuse
      get_url:
        url: "https://origin-repository.jboss.org/nexus/content/groups/ea/org/jboss/fuse/fuse-karaf/{{ fuse_version }}/fuse-karaf-{{ fuse_version }}.zip"
        dest: "{{ dest_dir }}/fuse-karaf-{{ fuse_version }}.zip"
        checksum: "{{ md5sum }}"

    - name: unarchive the Fuse distro
      command: "unzip {{ dest_dir }}/fuse-karaf-{{ fuse_version }}.zip -d {{ unzip_dest_dir }}"
      register: unzip_result

    - name: print result
      debug:
        msg: "Unzipping distro {{ unzip_result }}"
