---
# tasks file for fuse7
  - yum:
      name: unzip
      state: latest

  - name: download Fuse
    get_url:
      url: "https://origin-repository.jboss.org/nexus/content/groups/ea/org/jboss/fuse/fuse-karaf/{{ fuse_version }}/fuse-karaf-{{ fuse_version }}.zip"
      dest: "{{ dest_dir }}/fuse-karaf-{{ fuse_version }}.zip"
      checksum: "{{ md5sum }}"

  - name: Ansible check directory exists.
    stat:
      path: "{{ unzip_dest_dir }}"
    register: file_details

  - debug:
      msg: "The directory {{ unzip_dest_dir }} exists"
    when: file_details.stat.exists

  - name: Create directory if it doesn't exists.
    file:
      path: "{{ unzip_dest_dir }}"
      state: directory
      recurse: yes
      force: yes
    when: not file_details.stat.exists 

  - name: Ansible unzip destination directory exists.
    stat:
      path: "{{ unzip_dest_dir }}/fuse-karaf-{{ fuse_version }}"
    register: unzipdir

  - name: unarchive the Fuse distro
    shell: "unzip -n {{ dest_dir }}/fuse-karaf-{{ fuse_version }}.zip -d {{ unzip_dest_dir }}"
    args:
      warn: false
    when: not unzipdir.stat.exists 

  - name: Override last mvn repo if the additional repositories are defined
    lineinfile:
      dest: '{{ unzip_dest_dir }}/fuse-karaf-{{ fuse_version }}/etc/org.ops4j.pax.url.mvn.cfg'
      line: '    https://repository.jboss.org/nexus/content/groups/ea@id=fuseearlyaccess, \'
      regexp: 'https://repository.jboss.org/nexus/content/groups/ea@id=fuseearlyaccess'

  - name: Add additional mvn repos
    lineinfile:
      dest: '{{ unzip_dest_dir }}/fuse-karaf-{{ fuse_version }}/etc/org.ops4j.pax.url.mvn.cfg'
      line: "{{ item }}"
      insertafter: 'https://repository.jboss.org/nexus/content/groups/ea@id=fuseearlyaccess,*'
      state: present
    with_items:
      - '{{ additional_maven_repositories }}'
    when: additional_maven_repositories is defined
