---
# tasks file for fuse7
  - yum:
      name: unzip
      state: latest

  - name: Ansible check Fuse 7 kit exists.
    stat:
      path: "{{ path_dir }}/{{ fuse_version }}.zip"
    register: fuse_kit_details

  - debug:
      msg: "The {{ path_dir }}/{{ fuse_version }}.zip doesn't exist"
    when: not fuse_kit_details.stat.exists
    failed_when: 

  - name: Ansible check directory exists.
    stat:
      path: "{{ unzip_dest_dir }}"
    register: file_details

  - debug:
      msg: "The directory {{ unzip_dest_dir }} exists"
    when: file_details.stat.exists

  - name: Create directory if it doesn't exists.
    file:
      path: "{{ unzip_dest_dir }}"
      state: directory
      recurse: yes
      force: yes
    when: not file_details.stat.exists 

  - name: Ansible unzip destination directory exists.
    stat:
      path: "{{ unzip_dest_dir }}/fuse-karaf-{{ fuse_version }}"
    register: unzipdir

  - name: unarchive the Fuse distro
    shell: "unzip -n {{ path_dir }}/{{ fuse_version }}.zip -d {{ unzip_dest_dir }}"
    args:
      warn: false
    when: not unzipdir.stat.exists 

  - name: Override last mvn repo if the additional repositories are defined
    lineinfile:
      dest: '{{ unzip_dest_dir }}/{{ fuse_version }}/etc/org.ops4j.pax.url.mvn.cfg'
      line: '    https://repository.jboss.org/nexus/content/groups/ea@id=fuseearlyaccess, \'
      regexp: 'https://repository.jboss.org/nexus/content/groups/ea@id=fuseearlyaccess'
    when: additional_maven_repositories is defined

  - name: Add additional mvn repos
    lineinfile:
      dest: '{{ unzip_dest_dir }}/{{ fuse_version }}/etc/org.ops4j.pax.url.mvn.cfg'
      line: "{{ item }}"
      insertafter: 'https://repository.jboss.org/nexus/content/groups/ea@id=fuseearlyaccess,*'
      state: present
    with_items:
      - '{{ additional_maven_repositories }}'
    when: additional_maven_repositories is defined

  - name: Override karaf.clean.all option if specified
    lineinfile:
      dest: '{{ unzip_dest_dir }}/{{ fuse_version }}/etc/system.properties'
      regexp: "karaf.clean.all = false"
      line: "karaf.clean.all = true"
    when: karaf_clean_all

  - name: Override karaf.clean.cache option if specified
    lineinfile:
      dest: '{{ unzip_dest_dir }}/{{ fuse_version }}/etc/system.properties'
      regexp: "karaf.clean.cache = false"
      line: "karaf.clean.cache = true"
    when: karaf_clean_cache

  - name: Enable Admin user
    lineinfile:
      dest: '{{ unzip_dest_dir }}/{{ fuse_version }}/etc/users.properties'
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
    with_items:
    - { regexp: '#admin = admin,_g_:admingroup', line: 'admin = admin,_g_:admingroup' }
    - { regexp: '#_g_\\:admingroup = group,admin,manager,viewer,systembundles,ssh', line: '_g_\:admingroup = group,admin,manager,viewer,systembundles,ssh' }
    when: enable_admin

  - name: Start Fuse
    command: '{{ unzip_dest_dir }}/{{ fuse_version }}/bin/start'
    when: start_fuse


